name: Build Multi-Platform

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            ext: .exe
          - os: macos-latest  
            name: macos
            ext: ''
          - os: ubuntu-latest
            name: linux
            ext: ''
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install deps
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build
      run: pyinstaller --onefile --console --name prompt-toolkit-${{ matrix.name }} src/cli.py
      
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: dist/prompt-toolkit-${{ matrix.name }}${{ matrix.ext }}
